[Colors] Re-work how colors are generated
antoniandre/wave-ui pull request #157
Opened 2024-06-12 22:53 UTC by DerrikMilligan

# Summary

This PR aims to standardize how wave treats colors across the board. Currently we have a beautiful color palette that was hand crafted with love by @antoniandre choosing the increments and offsets for each base color. However the shade generation that we're using for colors coming from JavaScript are using a different shading algorithm and only shading out 3 light and dark shades.

With these changes in place the color palette AND the colors coming from JavaScript will use the same algorithm and all generate the same number of shades.

# Rationale

There are several reasons behind proposing this change.
1. When trying to use colors as design tokens, such as using the colors `primary`, `secondary`, `success`, `deep-purple` and trying to do some consistent shading surrounding those colors, only having the 3 shades for configured colors is limiting when the range of 6 shades gives you so much fine grained control with the palette colors.
2. The math equation we're currently implementing to shade the colors coming from JavaScript doesn't work nearly as well as the shading done in SCSS. The `warning` status color ends up becoming yellow with it's `light3` shade. 
![image](https://github.com/antoniandre/wave-ui/assets/37845846/1f288656-c179-46d7-a5fe-60344ea3c39f)
3. Customizing the palette, if so desired, is difficult in it's present state

# New Configuration

With the changes proposed, we will now be able to have more control from the config on how colors are handled. Here is a screenshot from the new documentation page demonstrating the new possibilities:
![image](https://github.com/antoniandre/wave-ui/assets/37845846/b4b7533d-14d5-4dbc-ad4d-9cdd16de75cb)

I have brought over the `lighten` and `darken` functions from SCSS to JavaScript. These function almost identically (See note 2). And allow us to get the same functionality that @antoniandre had for generating the shades within SCSS. A user can define a base color, the light and dark `increment` values, and the light and dark `offset` values. Or they can stick to just using a hex color and the new shading will use the same defaults as outlined in the SCSS.

And now 6 shades are being generated per color. Here is an example of how the new shading looks on the status colors:
![image](https://github.com/antoniandre/wave-ui/assets/37845846/52e0e39c-e076-422e-8899-4932b9c160b9)

# Notes

1. This change removes the color generation from the SCSS file and makes the palette available to configure from JavaScript. This has some tradeoffs that we can discuss. It means that we'll have to generate the colors on the client when the page is first loading. So there's a bit more work on the client upfront. However it allows for customizing it which is awesome. I'm okay if we want to omit the palette portion of this change and leave it in SCSS, but I am always in favor of more customization.
2. In the SCSS @antoniandre was using the builtin `lighten` and `darken` methods which work well, however there are a few caveats with how they shade outlined in the [SCSS documentation](https://sass-lang.com/documentation/modules/color/#lighten):
  `Because lighten() is usually not the best way to make a color lighter, it’s not included directly in the new module system. However, if you have to preserve the existing behavior, lighten($color, $amount) can be written [adjust($color, $lightness: $amount)](https://sass-lang.com/documentation/modules/color/#adjust).`
  So the new JavaScript implementation follows the `adjust` method more closely using color mixing to get the shading. Because of this, the hex codes do not ALWAYS line up 1:1 between the old shading method and the new one for the palette. But they are VERY close. IMHO to have more consistency it's worth it

# Final thoughts

This is a large change and would likely require a major version bump because it could `break` peoples sites somewhat given that their color shades may vary.

If we want to have this be a little more opt-in we could add a `shadeCount` option for each color when you're defining them the more configurable way. This would let us maybe have defaults that mimic the current configuration and make it less of a breaking change but maintain the customization for those who desire it.

2024-06-24 13:30 UTC, antoniandre commented
Hi @DerrikMilligan,
Thanks for your PR and hard work again!

## TL;DR;
I'm open to add up to 6 shades per color if that helps (in the current javascript process), and to update the algorithm (even if it may change some color codes) if that makes sense, but not adding more work than that at runtime (no to moving SCSS work to JS).
I do always want to support new features and customization, but not if it has an impact (even a small one) on the overall efficiency. In the case there would be, we should discuss the benefits and tradeoffs, like below. :)

---

there are things that I agree with in this PR, like all the color adjustment to make it similar to SCSS calculation, and smarter lightening darkening than the one I have done if you have found a way :)
But one thing I try to avoid as much as possible is to make the init heavier.

Atm, this is the generated CSS output with no custom config:

```css
:root{--w-base-increment:4px;--w-css-scope:.w-app;background-color:rgb(var(--w-base-bg-color-rgb));color:rgb(var(--w-base-color-rgb))}:root[data-theme=light]{--w-base-bg-color-rgb:255,255,255;--w-base-color-rgb:0,0,0;--w-contrast-bg-color-rgb:0,0,0;--w-contrast-color-rgb:255,255,255;--w-caption-color-rgb:80,80,80,.7;--w-disabled-color-rgb:204,204,204}:root[data-theme=dark]{--w-base-bg-color-rgb:34,34,34;--w-base-color-rgb:255,255,255;--w-contrast-bg-color-rgb:255,255,255;--w-contrast-color-rgb:0,0,0;--w-caption-color-rgb:175,175,175,.7;--w-disabled-color-rgb:74,74,74}*{margin:0;outline:none;padding:0}body{overflow-x:hidden}a{text-decoration:none}.w-app{display:flex;flex-direction:column;min-height:100dvh;position:relative}.w-app,.w-app *,.w-app :after,.w-app :before{box-sizing:border-box}.w-app.row{flex-direction:row}.w-app.d-block{display:block}.w-app.align-center{align-items:center}.w-app.align-end{align-items:flex-end}.w-app.justify-center{justify-content:center}.w-app.justify-end{justify-content:flex-end}.w-app.justify-space-between{justify-content:space-between}.w-app.justify-space-around{justify-content:space-around}.w-app.justify-space-evenly{justify-content:space-evenly}.w-app.text-center{text-align:center}.w-app.text-right{text-align:right}.w-main{padding-left:12px;padding-right:12px}.w-app .headline,.w-app .title1{font-size:31px;font-weight:100;letter-spacing:1px}.w-app .title2{font-size:24px;font-weight:400}.w-app .title3{font-size:20px;font-weight:400}.w-app .title4{font-size:18px;font-weight:400}.w-app .title5{font-size:15px;font-weight:600}.w-app .body{font-size:14px;font-weight:400}.w-app .caption{color:rgb(var(--w-caption-color-rgb));font-size:12px;font-style:italic}.w-app .text-upper{text-transform:uppercase}.w-app .text-lower{text-transform:lowercase}.w-app .text-capitalize{text-transform:capitalize}.w-app .text-light{font-weight:400}.w-app .text-bold{font-weight:700}.w-app .text-italic{font-style:italic}.w-app .show{display:block}.w-app .hide{display:none}.w-app .spacer{flex-grow:1}.w-app .grow{flex-basis:auto;flex-grow:1}.w-app .no-grow{flex-grow:0}.w-app .shrink{flex-shrink:1}.w-app .no-shrink{flex-shrink:0}.w-app .fill-width{width:100%}.w-app .fill-height{height:100%}.w-app .basis-zero{flex-basis:0}.w-app .align-start{align-items:flex-start}.w-app .align-center{align-items:center}.w-app .align-end{align-items:flex-end}.w-app .align-self-start{align-self:flex-start}.w-app .align-self-center{align-self:center}.w-app .align-self-end{align-self:flex-end}.w-app .align-self-stretch{align-self:stretch}.w-app .justify-start{justify-content:flex-start}.w-app .justify-center{justify-content:center}.w-app .justify-end{justify-content:flex-end}.w-app .justify-space-between{justify-content:space-between}.w-app .justify-space-around{justify-content:space-around}.w-app .justify-space-evenly{justify-content:space-evenly}.w-app .text-left{text-align:left}.w-app .text-center{text-align:center}.w-app .text-right{text-align:right}.w-app .text-nowrap{white-space:nowrap}.w-app .lh0{line-height:1}.w-app .lh1{line-height:1.2}.w-app .lh2{line-height:1.4}.w-app .lh3{line-height:1.6}.w-app .lh4{line-height:1.8}.w-app .lh5{line-height:2}.w-app .d-flex{display:flex}.w-app .d-iflex{display:inline-flex}.w-app .d-block{display:block}.w-app .d-iblock{display:inline-block}.w-app .bd1{border:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd2{border:2px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd3{border:3px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd4{border:4px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd5{border:5px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd6{border:6px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdx1{border-left:1px solid rgba(var(--w-contrast-bg-color-rgb),.12);border-right:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdy1{border-bottom:1px solid rgba(var(--w-contrast-bg-color-rgb),.12);border-top:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdl1{border-left:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdr1{border-right:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdt1{border-top:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bdb1{border-bottom:1px solid rgba(var(--w-contrast-bg-color-rgb),.12)}.w-app .bd0{border:none}.w-app .bdrs1{border-radius:4px}.w-app .bdrs2{border-radius:8px}.w-app .bdrs3{border-radius:12px}.w-app .bdrs4{border-radius:16px}.w-app .bdrs5{border-radius:20px}.w-app .bdrs6{border-radius:24px}.w-app .bdrsr{border-radius:999em}.w-app .bdrsm{border-radius:100%}.w-app .bdrs0{border-radius:0}.w-app .sh-6{box-shadow:inset 0 0 24px #00000073}.w-app .sh-5{box-shadow:inset 0 0 20px #00000060}.w-app .sh-4{box-shadow:inset 0 0 16px #0000004d}.w-app .sh-3{box-shadow:inset 0 0 12px #00000039}.w-app .sh-2{box-shadow:inset 0 0 8px #00000026}.w-app .sh-1{box-shadow:inset 0 0 4px #00000026}.w-app .sh1{box-shadow:0 0 1px #0000001a,1px 1px 4px #00000026}.w-app .sh2{box-shadow:0 0 1px #0000001a,2px 2px 8px #00000026}.w-app .sh3{box-shadow:0 0 1px #0000001a,3px 3px 12px #00000039}.w-app .sh4{box-shadow:0 0 1px #0000001a,4px 4px 16px #0000004d}.w-app .sh5{box-shadow:0 0 1px #0000001a,5px 5px 20px #00000060}.w-app .sh6{box-shadow:0 0 1px #0000001a,6px 6px 24px #00000073}.w-app .sh0{box-shadow:none}.w-app .ma1{margin:4px}.w-app .ma-1{margin:-4px}.w-app .ma2{margin:8px}.w-app .ma-2{margin:-8px}.w-app .ma3{margin:12px}.w-app .ma-3{margin:-12px}.w-app .ma4{margin:16px}.w-app .ma-4{margin:-16px}.w-app .ma5{margin:20px}.w-app .ma-5{margin:-20px}.w-app .ma6{margin:24px}.w-app .ma-6{margin:-24px}.w-app .ma7{margin:28px}.w-app .ma-7{margin:-28px}.w-app .ma8{margin:32px}.w-app .ma-8{margin:-32px}.w-app .ma9{margin:36px}.w-app .ma-9{margin:-36px}.w-app .ma10{margin:40px}.w-app .ma-10{margin:-40px}.w-app .ma11{margin:44px}.w-app .ma-11{margin:-44px}.w-app .ma12{margin:48px}.w-app .ma-12{margin:-48px}.w-app .maa{margin:auto}.w-app .ma0{margin:0}.w-app .mx1{margin-left:4px;margin-right:4px}.w-app .my1{margin-bottom:4px;margin-top:4px}.w-app .mx-1{margin-left:-4px;margin-right:-4px}.w-app .my-1{margin-bottom:-4px;margin-top:-4px}.w-app .mx2{margin-left:8px;margin-right:8px}.w-app .my2{margin-bottom:8px;margin-top:8px}.w-app .mx-2{margin-left:-8px;margin-right:-8px}.w-app .my-2{margin-bottom:-8px;margin-top:-8px}.w-app .mx3{margin-left:12px;margin-right:12px}.w-app .my3{margin-bottom:12px;margin-top:12px}.w-app .mx-3{margin-left:-12px;margin-right:-12px}.w-app .my-3{margin-bottom:-12px;margin-top:-12px}.w-app .mx4{margin-left:16px;margin-right:16px}.w-app .my4{margin-bottom:16px;margin-top:16px}.w-app .mx-4{margin-left:-16px;margin-right:-16px}.w-app .my-4{margin-bottom:-16px;margin-top:-16px}.w-app .mx5{margin-left:20px;margin-right:20px}.w-app .my5{margin-bottom:20px;margin-top:20px}.w-app .mx-5{margin-left:-20px;margin-right:-20px}.w-app .my-5{margin-bottom:-20px;margin-top:-20px}.w-app .mx6{margin-left:24px;margin-right:24px}.w-app .my6{margin-bottom:24px;margin-top:24px}.w-app .mx-6{margin-left:-24px;margin-right:-24px [...]

2024-06-24 22:19 UTC, DerrikMilligan commented
I agree. I will revert the SCSS changes and keep the JS changes and see where we're at there.

2024-06-24 23:13 UTC, DerrikMilligan commented
Okay this has been updated to revert the SCSS colors being moved to JS. I agree that moving it added a lot of overhead.

2024-07-02 09:41 UTC, antoniandre commented
Hey @DerrikMilligan, thanks for this PR. I've reviewed and I'm ready to merge after you adjust a few things I've commented in your commits :)
let me know if you have further questions

2024-07-03 17:54 UTC, DerrikMilligan commented
I went through all the commits and didn't see any additional comments. What else were you specifically meaning you'd like to see adjusted?

Was it this section from your original comment?

> Also just a useful side note that the styles generated in the client side are divided in 2 <style>s appended to the header on load (you can dev tools inspect the Wave UI documentation and open the tag), in order to only recompute all the colors - not the global styles - on theme switch.

2024-07-04 07:00 UTC, antoniandre requested changes
I think you should be able to view my comments now, they were pending 😅

2024-07-16 21:25 UTC, DerrikMilligan commented on src/wave-ui/utils/config.js
We still need all the color functions in here. This implements the new algorithm to generate colors which is the same way SCSS does it.

2024-07-16 21:25 UTC, DerrikMilligan commented on src/wave-ui/utils/config.js
This was for testing. But it's the same values. We can remove it.

2024-07-16 21:27 UTC, DerrikMilligan commented on src/wave-ui/utils/colors.js
> +    console.error(`expected value from 0~255, got: ${value}`) ||
Okay that's updated! Good call. My bad.

2024-07-16 21:28 UTC, DerrikMilligan commented on src/wave-ui/utils/colors.js
> +  return /^#[0-9A-Fa-f]{6}([0-9A-Fa-f]{2})?$/.test(str)
Thanks the case insensitive flag is a better way to handle that!

2024-07-16 21:31 UTC, DerrikMilligan commented on src/wave-ui/utils/colors.js
> +    hasAlpha: hex.length === 9
The first character is the `#` so if we take a hex value like `#11223344` it's technically 9 in length. The `getColorFullHex` will expand a short hex string to match that format by using the `expandShortHex` method.

We could adjust how this works. I started from someone else's work here: https://gist.github.com/ktnyt/2573047b5b4c7c775f2be22326ebf6a8 and started modifying it from there.

2024-07-16 21:40 UTC, DerrikMilligan commented on src/wave-ui/utils/colors.js
> + * Convert RGB components to a hex color string
I have tried to include lots more examples in the comments as to what is happening.

2024-07-16 21:41 UTC, DerrikMilligan commented on src/wave-ui/utils/colors.js
> +export function darken (color, weight = 12.4) {
In `_colors.scss` you used `6.2` as the base value for `dark-increment`. The values here are just doubled as a baseline. So `12.4` for the darken and `15` for the lighten by doubling the `7.5` as your default `light-increment` value.

2024-07-16 21:45 UTC, DerrikMilligan commented on src/documentation/views/colors.vue
> +        v-for="({label, color, shades}, j) in colorPalette"
Done

2024-07-16 22:06 UTC, DerrikMilligan commented on src/documentation/views/colors.vue
> +            lightIncrement: 11,
So with this do you mean you'd rather have this become an accordion instead of the vertical dividers?

2024-07-30 16:20 UTC, antoniandre commented
Thanks for all the changes @DerrikMilligan, good work, I'll merge in. 
Regarding the shadesCount prop you mentioned, would be nice to not generate all the extra shades if we don't need, but setting a default of 6 (3 dark + 3 light) will still be inconsistent from the color palette shading. So let's leave it like that, and we can already disable all the shading together with `colorShades: false`. 👌

2024-07-30 16:20 UTC, merged

2024-07-30 16:29 UTC, antoniandre commented
Now published in 3.14.0!